parameters:
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    scrap.class: TuByuem\Skrobaczka\Command\Scrap
    client.class: Goutte\Client
services:
    event_dispatcher:
        class: %event_dispatcher.class%
        arguments:
            - @service_container
    scrap:
        class: %scrap.class%
        arguments:
            - @client
        tags:
            -
                name: console.command
    client:
        class: %client.class%