parameters:
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    scrap.class: TuByuem\Skrobaczka\Command\Scrap
    client.class: Goutte\Client
    action.visit_mainpage.class: TuByuem\Skrobaczka\Action\VisitMainpage
    action.login.class: TuByuem\Skrobaczka\Action\Login
services:
    event_dispatcher:
        class: %event_dispatcher.class%
        arguments:
            - @service_container
    scrap:
        class: %scrap.class%
        arguments:
            - @action.visit_mainpage
            - @action.login
        tags:
            -
                name: console.command
    client:
        class: %client.class%
    action.visit_mainpage:
        class: %action.visit_mainpage.class%
        arguments:
            - @client
    action.login:
        class: %action.login.class%
        arguments:
            - @client
            - @action.visit_mainpage
            - %login.options%